CREATE TABLE Users(
    UserID CHAR(36) PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    IsVerified BOOLEAN DEFAULT FALSE,
    Password VARCHAR(255) NOT NULL,
    Blocked BOOLEAN DEFAULT FALSE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DeletedAt TIMESTAMP NULL
);


CREATE TABLE Verifications(
    VerificationId CHAR(36) PRIMARY KEY,
    UserID CHAR(36) NOT NULL,
    OTP INT NOT NULL,
    ExpiresAt TIMESTAMP NOT NULL,
    IsUsed BOOLEAN DEFAULT FALSE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DeletedAt TIMESTAMP NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Alerts(
    AlertID CHAR(36) PRIMARY KEY,
    UserID CHAR(36) NOT NULL,
    Curreny VARCHAR(255) NOT NULL,
    Price DECIMAL(20, 5) NOT NULL,
    Status VARCHAR(10) NOT NULL DEFAULT 'created',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DeletedAt TIMESTAMP NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);